### ISSUE TITLE
Hi ! can you provide pre-trained models for coco benchmark ?

### ISSUE THREAD

**Issue by moonsh** [YanFangCS/CyCTR-Pytorch#2]
Hi, I couldn't find the trained model for coco benchmark so

I wonder you are able to share it.

Thank you

**Comment by GengDavid** [comment]
Hi, @moonsh 
We could only provide the trained models for 1-shot segmentation on COCO at this moment due to the limited time and resources to re-train the model with this re-implementation.  
You can find the models [here](https://drive.google.com/drive/folders/11SGaKwuDIZklhtCfr1uPfb9YhJUqbbvh?usp=sharing).

**Comment by moonsh** [comment]
Yes. That's enough. Thank you !!
